config/routes.rb
Rails.application.routes.draw do
  resources :pets
  get 'search/create'

  devise_for :users
  root 'welcome#index'
  resources 'puppies', :only => 'index'
  resources :items

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/buscador.rb
class Buscador < ApplicationRecord
end

app/models/pet.rb
class Pet < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :authy_authenticatable, :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :lockable, :timeoutable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  #skip_before_action :verify_authenticity_token, if: :json_request?
  protect_from_forgery with: :exception
    #:exception
end

app/controllers/pets_controller.rb
class PetsController < ApplicationController
  before_action :set_pet, only: [:show, :edit, :update, :destroy]

  # GET /pets
  # GET /pets.json
  def index
    @pets = Pet.all
  end

  # GET /pets/1
  # GET /pets/1.json
  def show
  end

  # GET /pets/new
  def new
    @pet = Pet.new
  end

  # GET /pets/1/edit
  def edit
  end

  # POST /pets
  # POST /pets.json
  def create
    @pet = Pet.new(pet_params)

    respond_to do |format|
      if @pet.save
        format.html { redirect_to @pet, notice: 'Pet was successfully created.' }
        format.json { render :show, status: :created, location: @pet }
      else
        format.html { render :new }
        format.json { render json: @pet.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pets/1
  # PATCH/PUT /pets/1.json
  def update
    respond_to do |format|
      if @pet.update(pet_params)
        format.html { redirect_to @pet, notice: 'Pet was successfully updated.' }
        format.json { render :show, status: :ok, location: @pet }
      else
        format.html { render :edit }
        format.json { render json: @pet.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pets/1
  # DELETE /pets/1.json
  def destroy
    @pet.destroy
    respond_to do |format|
      format.html { redirect_to pets_url, notice: 'Pet was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pet
      @pet = Pet.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def pet_params
      params.require(:pet).permit(:name, :race, :age, :size)
    end
end

app/controllers/puppies_controller.rb
class PuppiesController < ApplicationController
before_action :authenticate_user!
  def index
  end
end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  def create
  	palabra = "%#{params[:keyword]}%"

  	#@pets = Pet.where("name LIKE ? OR race LIKE ?",palabra,palabra)
  	@pets = Pet.where("name LIKE '#{params[:keyword]}%' OR race LIKE '#{params[:keyword]}%'")
  	#@pets = Pet.find(:all, :conditions =>"name LIKE palabra")
  	respond_to do |format|
  		format.html {redirect_to root_path}
  		format.json {render json: @pets}
  		format.js
  	end
  	#render json: @pets
  	#raise @pets.to_yaml
  	#@pets = Pet.where("name = #{palabra} OR race = ?",palabra,palabra)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  before_action :set_item, only: [:show, :update, :destroy]
  # GET /items
  def index
   
  end

  # GET /items/1
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pets_helper.rb
module PetsHelper
end

app/helpers/puppies_helper.rb
module PuppiesHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SuperSecretPuppies</title>
  <%= stylesheet_link_tag    'https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css', media: 'all', 'data-turbolinks-track' => true %>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'https://code.jquery.com/jquery-2.2.0.min.js', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <%=javascript_include_tag "https://www.authy.com/form.authy.min.js" %>
  <%=stylesheet_link_tag "https://www.authy.com/form.authy.min.css" %>

</head>
<body>
  <nav class="navbar navbar-inverse navbar-fixed-top">
    <div class="container">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <%= link_to "Super Secret Puppies", root_path, class: 'navbar-brand' %>
      </div>
      <div id="navbar" class="collapse navbar-collapse">
        <ul class="nav navbar-nav">
          <li><%= link_to "Home", root_path %></li>
          <li><%= link_to "Puppies", puppies_path %></li>
        </ul>
        <% if defined?(current_user) %>
          <ul class="nav navbar-nav navbar-right">
            <% if current_user %>
              <li class="navbar-text">Hello <%= current_user.email %></li>
              <li><%= link_to "Sign out", destroy_user_session_path %></li>
            <% else %>
              <li><%= link_to "Sign up", new_user_registration_path %></li>
              <li><%= link_to "Sign in", new_user_session_path %></li>
            <% end -%>
          </ul>
        <% end -%>
      </div><!--/.nav-collapse -->
    </div>
  </nav>

  <main class="container">

  <%= content_tag :div, flash[:notice], class: "flash bg-success" if flash[:notice] %>
  <%= content_tag :div, flash[:alert], class: "flash bg-danger" if flash[:alert] %>
    <%= yield %>
  </main>
</body>
</html>

app/views/pets/_form.html.erb
<%= form_with(model: pet, local: true) do |form| %>
  <% if pet.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(pet.errors.count, "error") %> prohibited this pet from being saved:</h2>

      <ul>
      <% pet.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :pet_name %>
  </div>

  <div class="field">
    <%= form.label :race %>
    <%= form.text_field :race, id: :pet_race %>
  </div>

  <div class="field">
    <%= form.label :age %>
    <%= form.number_field :age, id: :pet_age %>
  </div>

  <div class="field">
    <%= form.label :size %>
    <%= form.number_field :size, id: :pet_size %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/pets/_pet.html.erb
<div>
	<strong>
		<%= pet.name %>
		
	</strong>
	<%= link_to "ver", pet, style:"color:blue;text-decoration:underline;" %>
</div>

app/views/pets/edit.html.erb
<h1>Editing Pet</h1>

<%= render 'form', pet: @pet %>

<%= link_to 'Show', @pet %> |
<%= link_to 'Back', pets_path %>

app/views/pets/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Pets</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Race</th>
      <th>Age</th>
      <th>Size</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @pets.each do |pet| %>
      <tr>
        <td><%= pet.name %></td>
        <td><%= pet.race %></td>
        <td><%= pet.age %></td>
        <td><%= pet.size %></td>
        <td><%= link_to 'Show', pet %></td>
        <td><%= link_to 'Edit', edit_pet_path(pet) %></td>
        <td><%= link_to 'Destroy', pet, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Pet', new_pet_path %>

app/views/pets/new.html.erb
<h1>New Pet</h1>

<%= render 'form', pet: @pet %>

<%= link_to 'Back', pets_path %>

app/views/pets/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @pet.name %>
</p>

<p>
  <strong>Race:</strong>
  <%= @pet.race %>
</p>

<p>
  <strong>Age:</strong>
  <%= @pet.age %>
</p>

<p>
  <strong>Size:</strong>
  <%= @pet.size %>
</p>

<%= link_to 'Edit', edit_pet_path(@pet) %> |
<%= link_to 'Back', pets_path %>

app/views/puppies/index.html.erb
<h1>Puppies</h1>
<p>Here are those pictures you were after.</p>

<ul class="row list-unstyled puppies">
  <% 8.times do |n| %>
    <li class="col-md-3 col-sm-6 col-xs-6">
      <%= image_tag "puppies/#{n+1}.jpg", class: "img-thumbnail img-responsive" %>
    </li>
  <% end %>
</ul>

app/views/welcome/index.html.erb
<div class="jumbotron">
  <h1>Super Secret Puppies</h1>
  <p>All the puppies you could need, kept safe under lock and key.</p>
  <%= link_to "See the puppies now!", puppies_path, class: "btn btn-primary btn-lg" %>
</div>

<div class="row">
  <div class="col-md-4">
    <h2>Premium puppy pics</h2>
    <p>You know who you are and you know what you want. You want pictures of
    puppies and this site is the site for you.</p>
  </div>
  <div class="col-md-4">
    <h2>Free user accounts</h2>
    <p>Pictures of puppies are great, but signing up to see them in order to
    keep those pictures secure is even greater.</p>
  </div>
  <div class="col-md-4">
    <h2>Some third benefit</h2>
    <p>Marketing sites usually have a third thing here, but when you already
    have puppies and security, you only need two features.</p>
  </div>
  <div class="col-md-4">
    <div id="resultados">
      
    </div>
     <%= form_tag "search/create", method: :get, remote: true, id: "search-form" do %>
     <%= text_field_tag :keyword, nil , placeholder: "Que estas buscando "%>
     <%= content_tag :button, type: :submit do %>
     Buscar 
     <%end%>
  <%end%>
 </div>
</div>